### Ein neues Produkt anlegen
GRAPHQL {{baseUrl}}/graphql

mutation {
  create(
    input: {
      name: "Graphql"
      erscheinungsdatum: "2022-02-01"
      homepage: "https://graphql.de"
      umsatz: {
        betrag: "200"
        waehrung: "EUR"
        }
      angestellterId: "00000000-0000-0000-0000-000000000001"
      angestellterNachname: "GraphQL"
      angestellterEmail: "graphql@mutation.de"
    }
  ) {
    id
  }
}

### Ein neues Produkt mit fehlerhaften Daten anlegen
GRAPHQL {{baseUrl}}/graphql

mutation {
  create(
    input: {
      name: "?!:"
      erscheinungsdatum: "2022-02-01"
      homepage: "https://graphql.de"
      umsatz: {
        betrag: "1"
        waehrung: "EUR"
      }
      angestellterId: "00000000-0000-0000-0000-000000000001"
      angestellterNachname: "123"
      angestellterEmail: "falscheEmail"
    }
  ) {
    id
  }
}
