### Ein Produkt mittels PUT aktualisieren: 204
PUT {{baseUrl}}/rest/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json

< data/produkt-30-put.json


### Ein nicht-vorhandenen Produkt mittels PUT aktualisieren: 404 (Not Found)
PUT {{baseUrl}}/rest/ffffffff-ffff-ffff-ffff-ffffffffffff
If-Match: ""0"
Content-Type: application/json

< data/produkt-30-put.json


### Ein Produkt mittels PUT und ungueltigen Daten aktualisieren: 422 (Unprocessable Entity)
PUT {{baseUrl}}/rest/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json

< data/produkt-30-put-invalid.json
