### Suche mit vorhandener Produkt-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkt(id: "00000000-0000-0000-0000-000000000001") {
    name
  }
}

### Suche mit nicht-vorhandener Produkt-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkt(id: "ffffffff-ffff-ffff-ffff-ffffffffffff") {
    name
  }
}

### Suche mit vorhandener Produkt-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkt(id: "00000000-0000-0000-0000-000000000001") {
    name
    erscheinungsdatum
    homepage
    umsatz {
      betrag
      waehrung
    }
  }
}

### Suche alle Produkte als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkte(input: {}) {
    id
    name
    erscheinungsdatum
    homepage
    umsatz {
      betrag
      waehrung
    }
  }
}

### Suche Produkte mit dem Namen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkte(input: {name: "a"}) {
    id
    name
    erscheinungsdatum
    homepage
    umsatz {
      betrag
      waehrung
    }
  }
}
### Suche Produkte mit nicht-vorhandenem Namen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  produkte(input: {name: "Nichtvorhanden"}) {
    id
  }
}
